# vim: set expandtab tabstop=2 shiftwidth=2:

title: Borderlands Modding
url: http://gittest.apocalyptech.com
description: >-
  All about Borderlands modding, primarily for Borderlands 2
  and The Pre-Sequel.
remote_theme: apocalyptech/blcm-web-theme
minimal_mistakes_skin: dark
include: ["_pages"]
breadcrumbs: true

# The example minimal_mistakes theme uses this, so why not?
markdown: kramdown

# Apparently for our theme, these plugins may be needed
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Footer Links
footer:
  links:
    - label: "BL2 + TPS Mods @ Github"
      url: "https://github.com/BLCM/BLCMods"
    - label: "BL2 Mods @ Nexus"
      url: "https://www.nexusmods.com/borderlands2"
    - label: "TPS Mods @ Nexus"
      url: "https://www.nexusmods.com/borderlandspresequel/"
      
# Defaults for various page types
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
