title: Borderlands Modding
description: >-
    All about Borderlands modding, primarily for Borderlands 2
    and The Pre-Sequel.
remote_theme: apocalyptech/blcm-web-theme
minimal_mistakes_skin: dark

# The example minimal_mistakes theme uses this, so why not?
markdown: kramdown

# Apparently for our theme, these plugins may be needed
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
